[package]
name = "alkahest-data"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alkahest-pm = { path = "../alkahest-pm" }
anyhow.workspace = true
binrw.workspace = true
bitflags.workspace = true
destiny-pkg.workspace = true
glam.workspace = true
lazy_static.workspace = true
tiger-parse.workspace = true
rustc-hash.workspace = true
rayon.workspace = true
bevy_ecs = { workspace = true, optional = true }

[features]
bevy = ["bevy_ecs"]
