[workspace]
resolver = "2"
members = [
    "crates/alkahest",
    "crates/alkahest-data",
    "crates/alkahest-panic-handler",
    "crates/alkahest-pm",
    "crates/alkahest-renderer",
    "crates/alkahest-test",
    "crates/destiny-havok",
    "crates/egui-directx11",
]

[workspace.dependencies]
anyhow = { version = "1.0.71" }
bevy_ecs = { git = "https://github.com/cohaereo/bevy.git", features = [
    "multi_threaded",
] }
bevy_tasks = { git = "https://github.com/cohaereo/bevy.git", features = [
    "multi_threaded",
] }
binrw = "0.13.3"
bitflags = { version = "2.5.0", features = ["serde"] }
bytemuck = "1.7.0"
chroma-dbg = "0.1.1"
crossbeam = "0.8.4"
destiny-pkg = "0.14"
tiger-parse = { version = "0.1.15", git = "https://github.com/v4nguard/tiger-parse", features = [
    "check_types",
    "check_types_strict",
    "destiny_pkg",
    "check_types_debug",
] }

# egui crates (make sure these are all the same version)
ecolor = "0.31"
egui = { version = "0.31", features = ["persistence"] }
egui_extras = "0.31"

field_access = "0.1.6"
glam = { version = "0.29", features = ["bytemuck", "mint", "fast-math"] }
itertools = "0.13.0"
lazy_static = "1.4.0"
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
parking_lot = "0.12.1"
png = "0.17.13"
# profiling = { version = "1.0.15", features = ["profile-with-tracy"] }
profiling = { version = "1.0.15", features = [] }
raw-window-handle = "0.6.0"
rayon = "1.7.0"
rustc-hash = "2.0.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.25"
smallvec = { version = "1.13.2", features = ["const_new"] }
thiserror = "1"
tracing = "0.1.37"
windows = { version = "0.57.0", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_UI_WindowsAndMessaging",
    "implement",
] }
winit = { version = "0.30" }


[profile.dev.package.destiny-pkg]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev]
# opt-level = 3
# cohae: Overflow checks are nice for some, but not for us
overflow-checks = false

[profile.release]
debug = "limited"
